### ISSUE TITLE
Nikon D3 is not recognized

### ISSUE THREAD

**Issue by aandreev0** [dognotdog/ptpwebcam#52]
Nikon D3 in S mode and Lv mode doesn't get recognized by PTP. No way to choose as a camera in QuickTIme or Zoom settings.

D3 LCD has "PC" text, and a progress bar running from left to right, signifying connection. I can browse D3 card through Finder.

(Positive control: Nikon D600 works great)

**Comment by dognotdog** [comment]
@aandreev0 The D3 appears to have a USB mode setting where it can be set to `Mass Storage` or `PTP`, can you check that the camera is in PTP mode?

<img width="785" alt="image" src="https://user-images.githubusercontent.com/1443151/95363958-30b5ae00-089e-11eb-9b55-57cc8e03a1ce.png">

Also, with `System Information`, can you check the USB `Product ID` that the camera shows (Hardware > USB > ...)?

**Comment by aandreev0** [comment]
Yes, that makes camera recognizable.
The autofocus however doesn't work (both with AF-D and AFS lenses) 
![image](https://user-images.githubusercontent.com/10820805/95370695-04923100-088e-11eb-89d3-b6c4e932c572.png)

**Comment by aandreev0** [comment]
Here's camera report

<script src="https://gist.github.com/aandreev0/e890e9be489a6daa9d43c1c82130be08.js"></script>

**Comment by dognotdog** [comment]
@aandreev0 the AF might work if you change `LiveView AF Miror Mode` to `Mirror-up for AF (tripod mode)`. This setting is specific to older Nikon cameras, where *hand-held mode* for some reason means use AF sensors that require LiveView to be off, and *tripod mode* should use LiveView focusing.

Also make sure both the lens and camera are in AF mode. Unfortunately the D3 does not support the `LiveView AF Mode` property, which would indicate if AF is unavailable because it's a manual lens, or because of a camera setting.

Also, just because the menu says `Autofocus unavailable`, you can still try it, and PTP Webcam will attempt to send the AF command to the camera.

**Comment by aandreev0** [comment]
OK, `Mirror-up for AF (tripod mode)` solves it. PTP still says "autofocus unavailable" but when you click, it works.

Thank you.
